---
- name: setup elastic
  hosts: all
  become: true
  become_method: sudo

  vars: 
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
    - name: Install packages
      apt: 
        update_cache: yes 
        name: "{{ packages }}" 
        state: present
      vars:
        packages:
        - openjdk-8-jre
        - apt-transport-https
        - wget
        - nginx

    - name: Add Elastic Apt Key
      apt_key: 
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic Repository
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
        state: present

    - name: Install Elasticsearch and Kibana
      apt: 
        update_cache: yes 
        name: "{{ packages }}" 
        state: present
      vars:
        packages:
        - elasticsearch
        - kibana

    - name: Add network.host entry 0.0.0.0 in  /etc/elasticsearch/elasticsearch.yml
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: 'network.host: 0.0.0.0'
        state: present
      notify: restart elasticsearch

    - name: Start elasticsearch
      service:
        name: elasticsearch
        state: started

    - name: Add server.host entry localhost in /etc/kibana/kibana.yml
      lineinfile:
        path: /etc/kibana/kibana.yml
        line: 'server.host: "localhost"'
        state: present
      notify:
        - restart kibana

    - name: Copy Nginx virtualhost file
      copy: 
        src: files/kibana.conf
        dest: /etc/nginx/sites-available/default
      notify:
        - restart nginx

  handlers:
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted

    - name: restart kibana
      service:
        name: kibana
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted

